import math
import heapq
import numpy as np

try:
    from src.planner.planning_types import PathPlan, PathReason
except Exception:
    from planner.planning_types import PathPlan, PathReason


class LocalPlanner:
    """
    Local geometric planner.

    LocalPlanner is a pure planner:
    - It receives current pose and an executable viewpoint.
    - It returns a structured PathPlan-compatible dict.
    - It does not output UAV actions.
    - It does not stop the episode.
    - It does not perform policy fallback.

    Strategy decisions such as changing target/viewpoint or lowering target
    priority must be handled by the planner feedback layer, not here.
    """

    def __init__(
        self,
        memory,
        unknown_cost=2.0,
        safety_weight=3.0,
        semantic_weight=0.3,
        visited_weight=0.2,
        blocked_safety_threshold=0.12,
        blocked_confidence_threshold=0.05,
        max_path_points=30,
        min_path_points=2,
        same_goal_distance=0.8,
    ):
        self.memory = memory
        self.unknown_cost = float(unknown_cost)
        self.safety_weight = float(safety_weight)
        self.semantic_weight = float(semantic_weight)
        self.visited_weight = float(visited_weight)
        self.blocked_safety_threshold = float(blocked_safety_threshold)
        self.blocked_confidence_threshold = float(blocked_confidence_threshold)
        self.max_path_points = int(max_path_points)
        self.min_path_points = int(min_path_points)
        self.same_goal_distance = float(same_goal_distance)

    def plan_path(self, current_pose, memory_target):
        """
        Plan a grid path from current pose to executable viewpoint.

        Args:
            current_pose:
                [x, y, z, yaw_degree]
            memory_target:
                Executable viewpoint dict generated by ViewpointPlanner.
                It must contain viewpoint_position or position.

        Returns:
            PathPlan-compatible dict.
        """
        if self.memory is None:
            return self.default_plan(reason=PathReason.NO_LOCAL_MAP)

        if current_pose is None or len(current_pose) < 3:
            return self.default_plan(reason=PathReason.INVALID_TARGET)

        if memory_target is None or not isinstance(memory_target, dict):
            return self.default_plan(reason=PathReason.INVALID_VIEWPOINT)

        if not memory_target.get("valid", False):
            return self.default_plan(
                reason=PathReason.INVALID_VIEWPOINT,
                debug={
                    "viewpoint_reason": memory_target.get(
                        "viewpoint_reason",
                        memory_target.get("reason", "")
                    )
                }
            )

        target_position = self.get_target_position(memory_target)
        if target_position is None:
            return self.default_plan(
                reason=PathReason.INVALID_VIEWPOINT,
                debug={
                    "viewpoint_type": memory_target.get("viewpoint_type", ""),
                    "viewpoint_reason": memory_target.get("viewpoint_reason", "")
                }
            )

        current_position = self.normalize_world_position(current_pose)
        if current_position is None:
            return self.default_plan(reason=PathReason.INVALID_TARGET)

        start_grid = self.memory.world_to_grid(current_position[0], current_position[1])
        goal_grid = self.memory.world_to_grid(target_position[0], target_position[1])

        if start_grid is None:
            return self.default_plan(
                reason=PathReason.OUTSIDE_MAP,
                target_position=target_position,
                debug={
                    "which": "start",
                    "current_pose": current_pose,
                    "target_position": target_position
                }
            )

        if goal_grid is None:
            return self.default_plan(
                reason=PathReason.OUTSIDE_MAP,
                start_grid=start_grid,
                target_position=target_position,
                debug={
                    "which": "goal",
                    "current_pose": current_pose,
                    "target_position": target_position,
                    "viewpoint_type": memory_target.get("viewpoint_type", "")
                }
            )

        if self.is_same_position(current_position, target_position):
            yaw_only_plan = self.build_yaw_only_plan(
                current_pose=current_pose,
                current_position=current_position,
                target_position=target_position,
                memory_target=memory_target,
                start_grid=start_grid,
                goal_grid=goal_grid
            )
            if yaw_only_plan is not None:
                return yaw_only_plan

            return self.default_plan(
                reason=PathReason.SAME_AS_CURRENT,
                start_grid=start_grid,
                goal_grid=goal_grid,
                target_position=target_position,
                debug={
                    "distance": self.distance_3d(current_position, target_position)
                }
            )

        cost_map, blocked_map = self.build_cost_map()

        if blocked_map[start_grid[0], start_grid[1]]:
            # The UAV is already at this cell. Treat current cell as free for
            # planning, but do not change the goal or strategy here.
            blocked_map[start_grid[0], start_grid[1]] = False

        if blocked_map[goal_grid[0], goal_grid[1]]:
            return self.default_plan(
                reason=PathReason.UNSAFE_GOAL,
                start_grid=start_grid,
                goal_grid=goal_grid,
                target_position=target_position,
                debug={
                    "viewpoint_type": memory_target.get("viewpoint_type", ""),
                    "viewpoint_position": memory_target.get("viewpoint_position", None),
                    "safety_score": memory_target.get("safety_score", None),
                    "blocked_safety_threshold": self.blocked_safety_threshold,
                    "blocked_confidence_threshold": self.blocked_confidence_threshold,
                }
            )

        grid_path = self.astar_search(
            start=start_grid,
            goal=goal_grid,
            cost_map=cost_map,
            blocked_map=blocked_map
        )

        if len(grid_path) == 0:
            return self.default_plan(
                reason=PathReason.ASTAR_FAILED,
                start_grid=start_grid,
                goal_grid=goal_grid,
                target_position=target_position,
                debug={
                    "viewpoint_type": memory_target.get("viewpoint_type", ""),
                    "viewpoint_position": memory_target.get("viewpoint_position", None),
                }
            )

        smooth_grid_path = self.smooth_path(grid_path, blocked_map)
        smooth_grid_path = self.downsample_path(smooth_grid_path, self.max_path_points)

        world_path = self.grid_path_to_world_path(
            grid_path=smooth_grid_path,
            z=current_position[2]
        )

        path_length = self.compute_world_path_length(world_path)

        if len(world_path) < self.min_path_points:
            return self.default_plan(
                reason=PathReason.PATH_TOO_SHORT,
                start_grid=start_grid,
                goal_grid=goal_grid,
                target_position=target_position,
                debug={
                    "raw_grid_path_len": len(grid_path),
                    "smooth_grid_path_len": len(smooth_grid_path),
                    "path_len": len(world_path),
                    "path_length": path_length
                }
            )

        plan = PathPlan(
            valid=True,
            reason=PathReason.OK,
            path=world_path,
            grid_path=smooth_grid_path,
            path_len=len(world_path),
            raw_grid_path_len=len(grid_path),
            path_length=round(path_length, 2),
            start_grid=start_grid,
            goal_grid=goal_grid,
            target_position=target_position,
            next_waypoint=self.select_next_waypoint(world_path, current_position),
            debug={
                "viewpoint_type": memory_target.get("viewpoint_type", ""),
                "viewpoint_position": memory_target.get("viewpoint_position", None),
                "viewpoint_yaw": memory_target.get("viewpoint_yaw", None),
                "anchor_position": memory_target.get("anchor_position", None),
                "safety_score": memory_target.get("safety_score", None),
                "information_gain": memory_target.get("information_gain", None),
            }
        )

        return plan.to_dict()

    def build_yaw_only_plan(
        self,
        current_pose,
        current_position,
        target_position,
        memory_target,
        start_grid,
        goal_grid,
    ):
        target_yaw = self.get_target_yaw(memory_target)
        if target_yaw is None:
            return None

        if len(current_pose) < 4:
            return None

        yaw_error = abs(self.normalize_angle(float(target_yaw) - float(current_pose[3])))
        if yaw_error < 3.0:
            return None

        plan = PathPlan(
            valid=True,
            reason=PathReason.OK,
            path=[current_position],
            grid_path=[start_grid],
            path_len=1,
            raw_grid_path_len=1,
            path_length=0.0,
            start_grid=start_grid,
            goal_grid=goal_grid,
            target_position=target_position,
            next_waypoint=current_position,
            debug={
                "path_kind": "yaw_only",
                "viewpoint_type": memory_target.get("viewpoint_type", ""),
                "viewpoint_position": memory_target.get("viewpoint_position", None),
                "viewpoint_yaw": target_yaw,
                "anchor_position": memory_target.get("anchor_position", None),
                "yaw_error": round(yaw_error, 2),
            }
        )

        data = plan.to_dict()
        data["viewpoint"] = memory_target.get("executable_viewpoint", memory_target)
        data["viewpoint_position"] = memory_target.get("viewpoint_position", None)
        data["viewpoint_type"] = memory_target.get("viewpoint_type", "")
        return data

    def get_target_yaw(self, memory_target):
        if not isinstance(memory_target, dict):
            return None

        executable_viewpoint = memory_target.get("executable_viewpoint", None)
        if isinstance(executable_viewpoint, dict):
            yaw = executable_viewpoint.get("yaw", None)
            if yaw is not None:
                try:
                    return float(yaw)
                except Exception:
                    pass

        for key in ["viewpoint_yaw", "target_yaw"]:
            yaw = memory_target.get(key, None)
            if yaw is None:
                continue
            try:
                return float(yaw)
            except Exception:
                continue

        return None

    def normalize_angle(self, angle):
        angle = float(angle)
        while angle > 180.0:
            angle -= 360.0
        while angle < -180.0:
            angle += 360.0
        return angle

    def get_target_position(self, memory_target):
        if not isinstance(memory_target, dict):
            return None

        executable_viewpoint = memory_target.get("executable_viewpoint", None)
        if isinstance(executable_viewpoint, dict):
            position = self.normalize_world_position(
                executable_viewpoint.get("position", None)
            )
            if position is not None:
                return position

        for key in ["viewpoint_position", "position"]:
            position = self.normalize_world_position(memory_target.get(key, None))
            if position is not None:
                return position

        return None

    def build_cost_map(self):
        confidence = np.clip(self.memory.confidence, 0.0, 1.0)
        safety = np.clip(self.memory.safety_value, 0.0, 1.0)
        semantic = np.clip(self.memory.semantic_value, 0.0, 1.0)

        observed_mask = confidence > 0.0

        cost_map = np.ones(
            (self.memory.grid_size, self.memory.grid_size),
            dtype=np.float32
        )
        cost_map = np.where(observed_mask, cost_map, self.unknown_cost)

        safety_cost = self.safety_weight * (1.0 - safety)
        semantic_bonus = self.semantic_weight * semantic
        visited_cost = np.where(self.memory.visited, self.visited_weight, 0.0)

        cost_map = cost_map + safety_cost + visited_cost - semantic_bonus
        cost_map = np.maximum(cost_map, 0.1)

        blocked_map = (
            (safety <= self.blocked_safety_threshold)
            & (confidence >= self.blocked_confidence_threshold)
        )

        return cost_map, blocked_map

    def astar_search(self, start, goal, cost_map, blocked_map):
        open_heap = []
        heapq.heappush(open_heap, (0.0, start))

        came_from = {}
        g_score = {
            start: 0.0
        }
        closed_set = set()

        while len(open_heap) > 0:
            current_f, current = heapq.heappop(open_heap)

            if current in closed_set:
                continue

            if current == goal:
                return self.reconstruct_path(came_from, current)

            closed_set.add(current)

            for neighbor in self.get_neighbors(current):
                nx, ny = neighbor
                if blocked_map[nx, ny]:
                    continue

                move_cost = self.get_move_cost(current, neighbor)
                tentative_g = g_score[current] + move_cost * float(cost_map[nx, ny])

                if neighbor not in g_score or tentative_g < g_score[neighbor]:
                    came_from[neighbor] = current
                    g_score[neighbor] = tentative_g
                    f_score = tentative_g + self.heuristic(neighbor, goal)
                    heapq.heappush(open_heap, (f_score, neighbor))

        return []

    def reconstruct_path(self, came_from, current):
        path = [current]

        while current in came_from:
            current = came_from[current]
            path.append(current)

        path.reverse()
        return path

    def get_neighbors(self, grid):
        gx, gy = grid
        offsets = [
            (-1, -1), (-1, 0), (-1, 1),
            (0, -1),           (0, 1),
            (1, -1),  (1, 0),  (1, 1)
        ]

        neighbors = []
        for dx, dy in offsets:
            nx = gx + dx
            ny = gy + dy

            if self.memory.in_bounds(nx, ny):
                neighbors.append((nx, ny))

        return neighbors

    def get_move_cost(self, grid_a, grid_b):
        ax, ay = grid_a
        bx, by = grid_b

        if ax != bx and ay != by:
            return math.sqrt(2.0)

        return 1.0

    def heuristic(self, grid, goal):
        gx, gy = grid
        tx, ty = goal
        return math.hypot(tx - gx, ty - gy)

    def smooth_path(self, grid_path, blocked_map):
        if len(grid_path) <= 2:
            return grid_path

        smooth_path = [grid_path[0]]
        anchor_idx = 0

        while anchor_idx < len(grid_path) - 1:
            next_idx = len(grid_path) - 1

            while next_idx > anchor_idx + 1:
                if self.has_line_of_sight(
                    grid_path[anchor_idx],
                    grid_path[next_idx],
                    blocked_map
                ):
                    break
                next_idx -= 1

            smooth_path.append(grid_path[next_idx])
            anchor_idx = next_idx

        return smooth_path

    def has_line_of_sight(self, start, end, blocked_map):
        cells = self.bresenham_line(start, end)

        for gx, gy in cells:
            if not self.memory.in_bounds(gx, gy):
                return False

            if blocked_map[gx, gy]:
                return False

        return True

    def bresenham_line(self, start, end):
        x0, y0 = start
        x1, y1 = end

        cells = []
        dx = abs(x1 - x0)
        dy = abs(y1 - y0)
        sx = 1 if x0 < x1 else -1
        sy = 1 if y0 < y1 else -1
        err = dx - dy
        x = x0
        y = y0

        while True:
            cells.append((x, y))

            if x == x1 and y == y1:
                break

            e2 = 2 * err
            if e2 > -dy:
                err -= dy
                x += sx
            if e2 < dx:
                err += dx
                y += sy

        return cells

    def downsample_path(self, grid_path, max_points):
        if len(grid_path) <= max_points:
            return grid_path

        indices = np.linspace(0, len(grid_path) - 1, max_points)
        indices = np.round(indices).astype(int).tolist()

        new_path = []
        last_idx = None

        for idx in indices:
            if idx == last_idx:
                continue

            new_path.append(grid_path[idx])
            last_idx = idx

        if new_path[-1] != grid_path[-1]:
            new_path.append(grid_path[-1])

        return new_path

    def grid_path_to_world_path(self, grid_path, z):
        world_path = []

        for gx, gy in grid_path:
            wx, wy = self.memory.grid_to_world(gx, gy)
            world_path.append((round(wx, 2), round(wy, 2), round(float(z), 2)))

        return world_path

    def compute_world_path_length(self, world_path):
        if len(world_path) <= 1:
            return 0.0

        total_length = 0.0

        for i in range(1, len(world_path)):
            x0, y0, z0 = world_path[i - 1]
            x1, y1, z1 = world_path[i]

            total_length += math.sqrt(
                (x1 - x0) ** 2
                + (y1 - y0) ** 2
                + (z1 - z0) ** 2
            )

        return total_length

    def select_next_waypoint(self, world_path, current_position):
        if len(world_path) == 0:
            return None

        for waypoint in world_path[1:]:
            if self.distance_3d(current_position, waypoint) > self.same_goal_distance:
                return waypoint

        return world_path[-1]

    def is_same_position(self, current_position, target_position):
        return self.distance_3d(current_position, target_position) <= self.same_goal_distance

    def distance_3d(self, point_a, point_b):
        return math.sqrt(
            (float(point_a[0]) - float(point_b[0])) ** 2
            + (float(point_a[1]) - float(point_b[1])) ** 2
            + (float(point_a[2]) - float(point_b[2])) ** 2
        )

    def normalize_world_position(self, position):
        if position is None:
            return None

        if not isinstance(position, (list, tuple)):
            return None

        if len(position) < 2:
            return None

        try:
            x = float(position[0])
            y = float(position[1])
            z = float(position[2]) if len(position) >= 3 else 0.0
        except Exception:
            return None

        return (round(x, 2), round(y, 2), round(z, 2))

    def default_plan(
        self,
        reason=PathReason.UNKNOWN,
        start_grid=None,
        goal_grid=None,
        target_position=None,
        debug=None,
    ):
        plan = PathPlan.invalid(
            reason=reason,
            debug=debug or {}
        )
        plan.start_grid = start_grid
        plan.goal_grid = goal_grid
        plan.target_position = target_position
        return plan.to_dict()
